server:
  port: 4244

spring:
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:mysql://localhost:3306/fgcdata
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver